services:
  postgres-primary:
    image: postgres:14
    container_name: postgres-primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: travelhub
    command: >
      postgres
        -c wal_level=replica
        -c max_wal_senders=3
        -c wal_keep_size=64
        -c listen_addresses=*
        -c hot_standby=on
        -c hba_file=/etc/postgresql/pg_hba.conf
    volumes:
      - primary_data:/var/lib/postgresql/data
      - ./primary/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    networks:
      - travelhub-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  # replica demuestra la estrategia de replicacion para disponibilidad
  postgres-replica:
    image: postgres:14
    container_name: postgres-replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      PGPASSWORD: replicator_pass
    volumes:
      - replica_data:/var/lib/postgresql/data
      - ./replica/init-replica.sh:/init-replica.sh
    ports:
      - "5433:5432"
    networks:
      - travelhub-net
    depends_on:
      postgres-primary:
        condition: service_healthy
    entrypoint: ["/bin/bash", "/init-replica.sh"]

  valkey:
    image: valkey/valkey:8.0
    container_name: valkey
    ports:
      - "6379:6379"
    networks:
      - travelhub-net
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # CACHE FALLBACK MOCK - demuestra la t√°ctica de cache
  # Lee desde postgres-replica, usa valkey como cache
  # comentado mientras se termina el mock
  # cache-fallback-mock:
  #   build: ./cache-fallback-mock
  #   container_name: cache-fallback-mock
  #   environment:
  #     DB_HOST: postgres-replica
  #     DB_PORT: 5432
  #     DB_NAME: travelhub
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres_pass
  #     VALKEY_HOST: valkey
  #     VALKEY_PORT: 6379
  #     CACHE_TTL: 30
  #   ports:
  #     - "5000:5000" # Accesible local desde localhost:5000
  #   networks:
  #     - travelhub-net
  #   depends_on:
  #     postgres-replica:
  #       condition: service_started
  #     valkey:
  #       condition: service_healthy

networks:
  travelhub-net:
    name: travelhub-net
    driver: bridge

volumes:
  primary_data:
  replica_data:
